\hypertarget{classException}{
\section{Exception Class Reference}
\label{classException}\index{Exception@{Exception}}
}


Inherits std::exception.\subsection*{Public Member Functions}
\begin{DoxyCompactItemize}
\item 
\hypertarget{classException_aa97328466ae0d1854f5ac67c3ca3934c}{
{\footnotesize template$<$typename T $>$ }\\{\bfseries Exception} (const char $\ast$fil, int lin, T const \&msg)}
\label{classException_aa97328466ae0d1854f5ac67c3ca3934c}

\item 
\hypertarget{classException_a89a13132f47004f0bda5c6ef90a1ddec}{
{\footnotesize template$<$typename T , typename... Args$>$ }\\{\bfseries Exception} (const char $\ast$fil, int lin, const char $\ast$msg, const T \&value, Args...args)}
\label{classException_a89a13132f47004f0bda5c6ef90a1ddec}

\item 
\hypertarget{classException_a45642915395d3b813fedc2593fbcb8bb}{
const char $\ast$ {\bfseries what} () const   throw ()}
\label{classException_a45642915395d3b813fedc2593fbcb8bb}

\end{DoxyCompactItemize}


The documentation for this class was generated from the following file:\begin{DoxyCompactItemize}
\item 
toolkit/exception/exception.hpp\end{DoxyCompactItemize}
